-- AlterTable
ALTER TABLE "products" ALTER COLUMN "price" SET DATA TYPE TEXT,
ALTER COLUMN "quantity" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "number" SET DATA TYPE TEXT,
ALTER COLUMN "phone" SET DATA TYPE TEXT;
